server:
  port: 8080

#spring配置
spring:
  datasource:
    username: aliyun2028857006
    password: 598949Lytxgz
    url: jdbc:mysql://rm-cn-pe33kbti0000njgo.rwlb.cn-chengdu.rds.aliyuncs.com:3306/online_book_shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# mybatis-plus的配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台输出sql语句
    # 启用 MyBatis-Plus 的 SQL 执行分析器
    sql-parser: com.baomidou.mybatisplus.extension.parsers.SqlExplainInterceptor
  type-aliases-package: com.bookStore.pojo
  global-config:
    db-config:
      logic-delete-field: isDeleted  #全局逻辑删除
      id-type: auto #主键策略自增长
      # 配置事务管理器
      transactionManagerType: org.springframework.jdbc.datasource.DataSourceTransactionManager


#jwt配置
jwt:
  token:
    tokenExpiration: 12000000 #有效时间,单位分钟
    tokenSignKey: headline123456  #当前程序签名秘钥 自定义

#综合排序参数自定义
comprehensiveOrder:
  #价格权重占0.6
  priceDiscount: 0.6f
  #销量权重占0.4
  saleVolumeDiscount: 0.4f

sky:
  #oss配置
  alioss:
    # 要带上 https:// ,上传时要使用的
    endpoint : https://oss-cn-chengdu.aliyuncs.com

    # 根据自己的帐号配置
    accessKeyId : LTAI5t7FeKrowJ85NXTJLuxp

    # 根据自己的帐号配置
    accessKeySecret : 0SkLNoUz3U2wFRHPRIKyd94HzS6Jsu

    # 存储空间名称
    bucketName : bookstore-picture

    # Bucket域名，访问文件时作为URL前缀，注意要加上 https:// 和 结尾带上 /
    urlPrefix : https://bookstore-picture.oss-cn-chengdu.aliyuncs.com/


#微信支付配置
wxpay:
  #商户号
  mch-id: 1561414331
  #应用号
  app-id: wxffb3637a228223b8
  #私钥字符串
  private-key: "-----BEGIN PRIVATE KEY-----
  MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDBHGgIh80193Gh
  dpD1LtMZfTRpcWI0fImyuBCyrd3gYb3rrsARebGcHdJsQA3mVjVqVp5ybhEZDPa4
  ecoK4Ye1hTppNpI/lmLt4/uUV/zhF5ahli7hi+116Ty6svHSbuMQBuUZeTFOwGrx
  jvofU/4pGIwh8ZvkcSnyOp9uX2177UVxDBkhgbZbJp9XF2b83vUa5eHo93CziPzn
  3hFdAlBCdTXB7DH+m0nN3Jou0szGukvq7cIgGpHku4ycKSTkIhhl9WRhN6OoSEJx
  q88MXzjkzTruc85PHN52aUTUifwg3T8Y4XqFQ61dTnEmgxeD2O6/pLdB9gLsp6yC
  GqN5Lqk7AgMBAAECggEBAL4X+WzUSbSjFS9NKNrCMjm4H1zgqTxjj6TnPkC1mGEl
  tjAHwLgzJBw62wWGdGhWWpSIGccpBBm1wjTMZpAZfF66fEpP1t1Ta6UjtGZNyvfF
  IZmE3jdWZ/WXGBnsxtFQKKKBNwrBW0Fbdqq9BQjLxLitmlxbmwrgPttcy855j6vZ
  qq4MBT1v8CtUT/gz4UWW2xWovVnmWOrRSScv7Nh0pMbRpPLkNHXrBwSSNz/keORz
  XB9JSm85wlkafa7n5/IJbdTml3A/uAgW3q3JZZQotHxQsYvD4Zb5Cnc9CPAXE5L2
  Yk877kVXZMGt5QPIVcPMj/72AMtaJT67Y0fN0RYHEGkCgYEA38BIGDY6pePgPbxB
  7N/l6Df0/OKPP0u8mqR4Q0aQD3VxeGiZUN1uWXEFKsKwlOxLfIFIFk1/6zQeC0xe
  tNTKk0gTL8hpMUTNkE7vI9gFWws2LY6DE86Lm0bdFEIwh6d7Fr7zZtyQKPzMsesC
  3XV9sdSUExEi5o/VwAyf+xZlOXcCgYEA3PGZYlILjg3esPNkhDz2wxFw432i8l/B
  CPD8ZtqIV9eguu4fVtFYcUVfawBb0T11RamJkc4eiSOqayC+2ehgb+GyRLJNK4Fq
  bFcsIT+CK0HlscZw51jrMR0MxTc4RzuOIMoYDeZqeGB6/YnNyG4pw2sD8bIwHm84
  06gtJsX/v10CgYAo8g3/aEUZQHcztPS3fU2cTkkl0ev24Ew2XGypmwsX2R0XtMSB
  uNPNyFHyvkgEKK2zrhDcC/ihuRraZHJcUyhzBViFgP5HBtk7VEaM36YzP/z9Hzw7
  bqu7kZ85atdoq6xpwC3Yn/o9le17jY8rqamD1mv2hUdGvAGYsHbCQxnpBwKBgHTk
  eaMUBzr7yZLS4p435tHje1dQVBJpaKaDYPZFrhbTZR0g+IGlNmaPLmFdCjbUjiPy
  A2+Znnwt227cHz0IfWUUAo3ny3419QkmwZlBkWuzbIO2mms7lwsf9G6uvV6qepKM
  eVd5TWEsokVbT/03k27pQmfwPxcK/wS0GFdIL/udAoGAOYdDqY5/aadWCyhzTGI6
  qXPLvC+fsJBPhK2RXyc+jYV0KmrEv4ewxlK5NksuFsNkyB7wlI1oMCa/xB3T/2vT
  BALgGFPi8BJqceUjtnTYtI4R2JIVEl08RtEJwyU5JZ2rvWcilsotVZYwfuLZ9Kfd
  hkTrgNxlp/KKkr+UuKce4Vs=
  -----END PRIVATE KEY-----"
  #营业执照序列号
  mch-serial-no: 25FBDE3EFD31B03A4377EB9A4A47C517969E6620
  #V3密钥
  api-v3-key: CZBK51236435wxpay435434323FFDuv3


