server:
  port: 8080

#spring配置
spring:
  datasource:
    username: aliyun2028857006
    password: 598949Lytxgz
    url: jdbc:mysql://rm-cn-pe33kbti0000njgo.rwlb.cn-chengdu.rds.aliyuncs.com:3306/online_book_shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bookStore.entity