server:
  port: 8080

#spring配置
spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER




mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bookStore.entity